### ISSUE TITLE
Compiler for AT (from script language)

### ISSUE THREAD

**Issue by balistof** [ciyam/AT#1]
Is there a compiler to generate the machine code from a scripting language?

**Comment by ciyam** [comment]
No - the AT code (https://github.com/ciyam/AT/blob/master/docs/_at.cpp.html) does disassembly only. There was a website called "smartcontr.actor" a few years back that would generate AT smart contracts for you (which I think is the better way to go anyway) but I don't think it exists now unfortunately.

I do also recall that @burstdev had built something that would take the op codes (like a mini-assembler) rather than having to use just machine code but I'm not sure what happened with that either.

**Comment by balistof** [comment]
Do you know by any chance who was behind smartcontr.actor? Would be a pity if this is lost now.

**Comment by ciyam** [comment]
That was created by @burstdev as well (he also contributed a bit to the development of the AT virtual CPU in terms of a few of the op codes and corrections to some inconsistencies). I am pretty sure that @vcbs did keep a copy of it somewhere so you could perhaps try contacting him about it. I will close this issue now but if you wish to contact me directly to ask further questions that would be fine (if you don't know how to PM me then contact @crowetic to get an invite to the CIYAM Slack).

**Comment by jjos2372** [comment]
Dear @ciyam and @balistof 

We have implemented an AT compiler/emulator/debugger, available here:
https://github.com/burst-apps-team/blocktalk

The user writes contracts directly in Java class and they are compiled into AT bytecode.

I hope you like it, all the best.
